#!/bin/sh
export PATH=$HOME/.config/emacs/bin:$PATH
export PATH=$HOME/node_volumes/.bin:$PATH
export PATH=$HOME/local/share/go/bin:$PATH
export GOPATH=$HOME/local/share/go
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.emacs.d/bin:$PATH
export PATH=$HOME/source:$PATH
export PATH="$HOME/bin:$PATH"
export PATH="/usr/src/acstall/distrobox/usr/binp:$PATH"
[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env" # ghcup-env
export PATH=$HOME/.ghcup/bin:$PATH
#eval "$(fnm env)"
eval "$(zoxide init zsh)"
#eval "`pip completion --zsh`"

# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('$HOME/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "$HOME/miniconda3/etc/profile.d/mamba.sh" ]; then
    . "$HOME/miniconda3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.elan/bin:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export PATH=/usr/src/acstall/distrobox/usr/binp:$PATH
export PATH=$HOME/source:$PATH
export PATH=$HOME/.nix-profile/bin:$PATH
export PATH=/var/lib/flatpak/exports/bin:$PATH
export PATH=/usr/lib/jvm/default/bin:$PATH
export PATH=/usr/bin/vendor_perl:$PATH
export PATH=/usr/bin/core_perl:$PATH
export PATH=/nix/var/nix/profiles/default/bin:$PATH
export PATH=/usr/local/sbin:$PATH
