#!/bin/sh
export PATH=$HOME/local/share/go/bin:$PATH
export GOPATH=$HOME/local/share/go
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.emacs.d/bin:$PATH
export PATH=$HOME/source:$PATH
export PATH=/usr/bin/julia-1.6.3/bin:$PATH
export BUN_INSTALL=/home/buddharta/.bun
export PATH="$BUN_INSTALL/bin:$PATH"
[ -f "/home/buddharta/.ghcup/env" ] && source "/home/buddharta/.ghcup/env" # ghcup-env
#eval "$(fnm env)"
eval "$(zoxide init zsh)"
#eval "`pip completion --zsh`"

export EMSDK_QUIET=1 

# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/buddharta/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/buddharta/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/buddharta/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/buddharta/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/home/buddharta/miniconda3/etc/profile.d/mamba.sh" ]; then
    . "/home/buddharta/miniconda3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

#emscripten hook
source "/home/buddharta/source/emsdk/emsdk_env.sh"
