#!/bin/sh
export PATH=$HOME/node_volumes/.bin:$PATH
export PATH=$HOME/local/share/go/bin:$PATH
export GOPATH=$HOME/local/share/go
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.emacs.d/bin:$PATH
export PATH=$HOME/source:$PATH
export PATH=/usr/bin/julia-1.6.3/bin:$PATH
export BUN_INSTALL=$HOME/.bun
export PATH="$BUN_INSTALL/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="/usr/src/acstall/distrobox/usr/binp:$PATH"
[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env" # ghcup-env
#eval "$(fnm env)"
eval "$(zoxide init zsh)"
#eval "`pip completion --zsh`"

# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('$HOME/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "$HOME/miniconda3/etc/profile.d/mamba.sh" ]; then
    . "$HOME/miniconda3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

