## FIRST LINE/ROW: Info & Status
# First param ─┌
format="""
$username\
$hostname\
$directory\
$fill\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$cmd_duration\
$time\
$line_break\
$character
"""
[username]
format = "[$user]($style)@"
style_user = "bold purple"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) ❯ "

style = "bold red"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = "blue"

[fill]
symbol = " "
# Before all the version info (python, nodejs, php, etc.)
[git_branch]
symbol = " "
format = "[$symbol $branch]($style) "
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
style = "purple"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

[git_metrics]
disabled = false

# Last param in the first line/row
[cmd_duration]
style="green"
min_time = 1
format = "[$duration]($style)"
disabled = false


## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
disabled = true

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 15
style = "bold red"
disabled = true

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 50
style = "bold yellow"
disabled = true

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
threshold = 80
style = "bold green"
disabled = true

# Prompt: optional param 1
[time]
format = "$time($style)"
time_format = "%T"
style = "yellow"
disabled = true

# Prompt: param 2 └─
[character]
success_symbol = " [λ❯](green)"
error_symbol = "[❯](red)"

# SYMBOLS
[status]
symbol = "[x](red)"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = true

[haskell]
symbol = "λ "
[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

#[git_branch]
#symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
